---
# Variables listed here are applicable to all host groups

# url_apt_key: "http://keyserver.ubuntu.com/pks/lookup?op=get&search="

# ntpserver: '0.fr.pool.ntp.org'

user: andy

web:
  httpd_port: 80
  domain: debian
  project_path: /home/andy/www

# php5:
#   php_date_timezone: 'America/Sao_Paulo'

mariadb:
  login_user: root
  login_password : ''
#   current_password: ''
#   root_password: dev


nodejs_version: "14.x"

apt_keyserver: "hkp://p80.pool.sks-keyservers.net:80"