---

- hosts: debian
  vars_files:
    - group_vars/all.yml

  roles:

    - common       # List of essential packages
    - design       # Design pack
    - composer
    # - nodejs    # commented out for now
    # - browsers
    # - dev
    - multimedia
    - virtualization
    - awesome
    # - sublime
    - php
    - ufw
    # - mysql
    # - aws
    - new
    # - allPackages # 5000+ packages slow!!



    #- users
    #- latex        # Latex and ide texmaker


# - name: jackett from galaxy
#   hosts: all
#   tags: jackett
#   roles:
#     - { role: chrisjohnson00.jackett, tags: ["jackett"]}
#   become: yes

- name: Install minikube
  hosts: all
  roles:
    - role: gantsign.minikube 
  tags: aws
  become: yes

- name: Install helm
  hosts: all
  roles:
    - role: geerlingguy.helm
  tags: aws
  become: yes
