---

- name: Google Chrome | Pre requirements
  apt:
    name: gnupg
    state: present
  become: true
  become_method: su

- name: Google Chrome | Add gpg
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  become_method: su

- name: Google Chrome | Apt Repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    update_cache: true
  become: true
  become_method: su

- name: Google Chrome | Installing latest version
  apt:
    name: google-chrome-stable
    state: present
  become: true

- name: install brave the apt key
  become: true
  become_method: su
  shell: curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

- name: install brave add the apt repository
  become: true
  become_method: su
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main  
    state: present

- name: Install Brave
  become: yes
  become_method: su
  apt:
    name: brave-browser
    state: latest
    update_cache: yes

# Repositorio do Opera

- name: Importando a chave do repositorio do Opera
  apt_key: 
    url: https://deb.opera.com/archive.key
    state: present
  become: true
  tags:
    - repo
    - opera
    - web

- name: Adicionando o Repositorio do Opera
  apt_repository:
    repo: "deb [arch=amd64] https://deb.opera.com/opera-stable/ stable non-free"
    state: present
    filename: opera-stable
  become: true
  tags:
    - repo
    - opera
    - web




# Instalação do Opera

- name: Instalando o Opera
  apt:
    name: opera-stable
    state: present
    update_cache: yes
  become: true
  tags:
    - opera
    - web




    
