---

#- name: Google Chrome | Install lists packages
#  dnf:
#    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
#    state: installed
#    disable_gpg_check: yes

- name: install|deb| add the apt key
  become: true
  shell: curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

- name: install|deb| add the apt repository
  become: true
  #shell: echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" > /etc/apt/sources.list.d/brave-browser-release.list
  apt_repository:
    repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main  
    state: present

- name: Install Brave
  become: yes
  apt:
    name: brave-browser
    state: latest
    update_cache: yes
