---

- name: Virtualization | Install lists packages
  apt:
    name:
      - gnome-boxes
      - vagrant
      - podman
      - buildah
      - docker
      - docker-compose
      - binutils
      - gcc
      - make
      - cmake
      - golang-go
      - patch
    state: latest

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes

