---
- name: install packages
  apt:
    name:
      - apache2
      - default-mysql-server
      - python3-pymysql
      - php
      - php-mysql
      - libapache2-mod-php
      - ufw
      - php-mbstring
      - php-bcmath
      - php-xml 
    state: present
    cache_valid_time: 3600
  become: True

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present
    ignore_configcheck: True
  become: True

- name: Enable the Apache2 module rewrite
  community.general.apache2_module:
    state: present
    name: rewrite
  become: True


# install php8.0

- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  become: True

- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    id: 15058500A0235D97F5D10063B188E2B695BD4743
    state: present
  become: True

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  become: True

- name: Update apt caches after repo is added (Debian).
  apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
  become: True

- name: install php 8.0 packages
  apt:
    name:
      - php8.0
      - php-mysql
      - libapache2-mod-php
      - php8.0-mysql
      - php8.0-cli
      - php8.0-common
      - php8.0-snmp
      - php8.0-ldap
      - php8.0-curl
      - php8.0-mbstring
      - php8.0-zip
      - php8.0-tidy
      - php8.0-opcache
      - php8.0-xml
      - php8.0-fpm 
      - libapache2-mod-php8.0
    state: present
    cache_valid_time: 3600
  become: True

- name: Enable the Apache2 module for php8.0
  apache2_module:
    name: 'php8.0'
    state: present
    ignore_configcheck: True
  become: True

- name: ensure apache is restarted
  service:
    name: apache2
    state: restarted
  become: True
